#!/usr/local/bin/php
<?php
//local用 #!/usr/bin/php
date_default_timezone_set('Asia/Tokyo');
require_once (dirname(__FILE__) . '/app/Users.php');
$users = new Users();
if(!isset($argv[1])){
	$limit = 20;
}else{
	$limit = $argv[1];
}
$user_list = $users->get_star_update_queue_list($limit);
$result = HatenaAPI::fetch_hateb_user_info($user_list);
foreach ($user_list  as $user) {
	if($result[$user['name']]['star'] !== false && $result[$user['name']]['followers'] !== false){
		$users->update_user_star($user, $result[$user['name']]['star'], $result[$user['name']]['followers']);
	}
}
$users->update_scores();
$users->update_users_karma();
//$users->update_all($limit);
//echo count($queue_list) . 'users updated';
?>