#!/usr/local/bin/php
<?php
//local用 #!/usr/bin/php
date_default_timezone_set('Asia/Tokyo');
require_once (dirname(__FILE__) . '/app/Feed.php');
$feed = new Feed();
$feed->update_feed();
$cache = new Cache(FEED_CACHE_EXPIRES, true, FEED_CACHE_DIR);
$hotentry = $feed->get_feed_data('hotentry');
$new = $feed->get_feed_data('new');
$cache->sweap_old_cache(true);
$cache->save_cache('hotentry', $hotentry);
$cache->save_cache('hotentry', $hotentry, true);
$cache->save_cache('new', $new);
$cache->save_cache('new', $new, true);
?>